### ISSUE TITLE
The binary uses an SDK older than the 10.9 SDK

### ISSUE THREAD

**Issue by LEPINARD** [miyako/4d-plugin-sfml-audio#2]
Hello Mr. MIYAKO,
We cannot have the plugins notarized
"4d-plugin-sfml-audio"
for Catalina. Aple's answer is:
"The binary uses an SDK older than the 10.9 SDK."
Best regards

**Comment by miyako** [comment]
3rd party frameworks distributed with SFML are all using an older SDK.
simply recompiling the plugin will not solve it.

```sh
otool -l libsfml-system.2.5.1.dylib
```

reveals 

version 10.7
      sdk 10.7

**Comment by miyako** [comment]
FLAC.framework
freetype.framework
ogg.framework
OpenAL.framework
vorbis.framework
vorbisenc.framework
vorbisfile.framework

**Comment by miyako** [comment]
- [x] use Apple system OpenAL

- [x] build static version of libvorbis, libogg, flac

**Comment by miyako** [comment]
could you please test 3.0 and report here if it works or not? 

https://github.com/miyako/4d-plugin-sfml-audio/releases

**Comment by LEPINARD** [comment]
Hello,
Thank you for version 3. I did not try to write it down because it no longer records any sound (4D v18).
Sound playback works.
Greetings
Thierry

**Comment by miyako** [comment]
keep in mind that access to the microphone requires special entitlement.

you need to code sign your app or 4D

<img width="780" alt="Screen Shot 2020-02-15 at 1 36 21" src="https://user-images.githubusercontent.com/1725068/74549808-a7124280-4f93-11ea-83a8-dacdc8a7a961.png">

**Comment by LEPINARD** [comment]
Thank you but how do you sign 4D V18 code ?
(It is a great honor to be able to converse with a 4D star like you 👍 )

**Comment by miyako** [comment]
you already know how to code sign your built app in v18.

``SignApp.sh`` which is inside 4D.app, 

uses ``4D.entitlements`` inside Contents/Resources.

<img width="712" alt="Screen Shot 2020-02-15 at 13 10 56" src="https://user-images.githubusercontent.com/1725068/74581613-a5c53200-4ff4-11ea-83ee-fef682c304ab.png">

if you want to access audio input from 4D, 
you should code sign 4D itself using the same methodology.

**Comment by LEPINARD** [comment]
Mister Miyako,
Thanks for your help.
We signed 4D, we signed our application, it never appears in system preferences.
Do you have a working sample application?
We are using MacOS 10.14 but our tests in 10.15 are no better.
Thank you in advance.
Best regards.

**Comment by miyako** [comment]
how exactly did you sign your app?

also what is its app id?

if you think your app is already remembered as "not allowed access) 
you can reset security and privacy settings like so: 

```sh
tccutil reset All com.4d.4d
tccutil reset All com.4D.4DServer
```

**Comment by miyako** [comment]
also, you could disable code sign in 4D build application dialog,

and use https://github.com/miyako/4d-utility-build-application instead
